updateFrequency: 5
fixedMaterials:
# ground layers
  - BEDROCK
  - LIME_CONCRETE
# blocks that change / cause others to change easily
  - GRASS
  - GRASS_BLOCK
  - DIRT
  - COARSE_DIRT
  - FARMLAND
  - DIRT_PATH
# potentially dangerous
  - TNT
  - LAVA
  - WATER
# used in the house experiment
  - RED_WOOL
  - BLACK_WOOL
  - YELLOW_WOOL
  - BLUE_WOOL
  - STONE_BRICKS

clientPort: 2802

worldFilePath: /de/saar/minecraft/worlds/

startInventory:
  - STONE

banPlayers: true

NotBannedPlayers:
  - Trillian04
  - NRCelty
  - Just4Fun1998
  - Minecraft_UdS_1
  - Minecraft_UdS_2
  - Minecraft_UdS_3
  - Minecraft_UdS_4
  - Minecraft_UdS_5
